### ISSUE TITLE
hdf5_io issue: read binary string of boundary condition

### ISSUE THREAD

**Issue by Memcys** [tenpy/tenpy#117]
**Describe the bug**
I was trying to load a MPS from an HDF5 file, when I came into a `ValueError` (and sometimes other errors).
It is noteworthy that this issue comes with the `0.7.2.dev47` branch, while the **released** `0.7.2` works well.

**Minimal example or code extract**
```python
import h5py
from tenpy.tools import hdf5_io
from tenpy.networks.mps import MPS
from tenpy.models.tf_ising import TFIChain

N = 16  # number of sites
model = TFIChain({"L": N, "J": 1., "g": 1., "bc_MPS": "finite"})
sites = model.lat.mps_sites()
psi = MPS.from_product_state(sites, ['up'] * N, "finite")
f = "psi.h5"

# Save to file
with h5py.File(f, 'w') as r:
    hdf5_io.save_to_hdf5(r, psi)
# Load from file
with h5py.File(f, 'r') as r:
    psi2 = hdf5_io.load_from_hdf5(r, psi)
```

**Error traceback**
```
<ipython-input-30-909c2a388b55> in <module>
      1 with h5py.File(f, 'r') as r:
----> 2     psi2 = hdf5_io.load_from_hdf5(r)
      3

...

.../lib/python3.7/site-packages/physics_tenpy-0.7.2.dev0+bdec68a-py3.7-linux-x86_64.egg/tenpy/networks/mps.py in test_sanity(self)
    201         """Sanity check, raises ValueErrors, if something is wrong."""
    202         if self.bc not in self._valid_bc:
--> 203             raise ValueError("invalid boundary condition: " + repr(self.bc))
    204         if len(self._B) != self.L:
    205             raise ValueError("wrong len of self._B")

ValueError: invalid boundary condition: "b'infinite'"
```
or one might catch such an error:
```
.../lib64/python3.9/site-packages/h5py/_hl/base.py in _e(self, name, lcpl)
    198         else:
    199             try:
--> 200                 name = name.encode('ascii')
    201                 coding = h5t.CSET_ASCII
    202             except UnicodeEncodeError:

AttributeError: 'MPS' object has no attribute 'encode'
```

As I mentioned, for the `0.7.2` release `psi` gets loaded successfully.

**Comment by jhauschild** [comment]
Hmm, this looks like an issue of encoding strings, the `b'infinite'` is a raw binary string while we expected an encoding as usual (UTF8) strings `'infinite'`.
While `tenpy.tools.hdf5_io` has indeed changed since v0.7.2, there was no change that might cause this difference - it only added the feature that general objects supporting the pickle protocol could be saved to HDF5.

Can you try to run the test for the export/import?
Simply go into the `tests/export_import_test` folder and run `pytest` (provided that pytest is installed). Do those tests fail?

Is there a possibility that the version of the underlying `h5py` or HDF5 changed when you switched between v0.7.2 and the latest git version?

**Comment by Memcys** [comment]
> Can you try to run the test for the export/import?

Thank you for reminding me. The test failed for `test_hdf5.py`:
```
...
    def test_sanity(self):
        """Sanity check, raises ValueErrors, if something is wrong."""
        assert self.L == len(self.sites)
        if self.bc not in self._valid_bc:
>           raise ValueError("invalid MPO boundary conditions: " + repr(self.bc))
E           ValueError: invalid MPO boundary conditions: "b'infinite'"

.../lib64/python3.9/site-packages/physics_tenpy-0.7.2.dev47+bdec68a-py3.9-linux-x86_64.egg/tenpy/networks/mpo.py:298: ValueError
```

---

> Is there a possibility that the version of the underlying `h5py` or HDF5 changed when you switched between v0.7.2 and the latest git version?

I have noticed the same issue in both the following situations:
1. an virtual environment which installs (via pip) the required packages except for `physics-tenpy`, then run `python setup.py install` under `tenpy` root;
2. a virtual environment which installs (via conda) all the required packages including `physics-tenpy`, then uninstall `physics-tenpy`, and run `python setup.py install` under `tenpy` root.

I checked the version of `h5py`, which was `3.1.0`. As I rolled back to `2.10.0` via `pip`, it *passed*. Nevertheless, running the previous code it still catches
```
AttributeError: 'MPS' object has no attribute 'encode'
```
Worse still, something strange happened:

1. After an `AttributeError`, I ran
    ```python
    # Load from file
    with h5py.File(f, 'r') as r:
        psi2 = hdf5_io.load_from_hdf5(r, psi)
    ```
    which **succeeded**.
2. I upgraded `h5py` to `3.1.0`, and ran the code again. This time, `hdf5_io.load_from_hdf5()` kept reporting the above `AttributeError`.

**Comment by Memcys** [comment]
Cheers!

This time for `h5py-2.10.0` it *ultimately* **read out the MPS**, before many times I tried upgrading and downgrading `h5py`---I might have sometimes restarted `ipython` in between, though I'm not that sure.

Solution
-----------
- [x] use `h5py-2.10.0`

I would like to remind anyone who comes here that at least for `tenpy-0.7.2` and development versions named after it, **lock**  `h5py` to version `2.10.0`.

---
I will close this issue in a day, if there is no relevant troubles.

**Comment by jhauschild** [comment]
Indeed, h5py >= 3.0 changed the way string encodings worked, loading a data set just returned the raw string instead of the encoded one. I've added a corresponding fix in hdf5_io, such that it works with h5py >=3.0 again.

Can you please confirm that it now works with new versions of h5py again?
Then you can close the issue.
Thank you!

**Comment by Memcys** [comment]
Thank you for your efficient fix. It now works as expected.

The `AttributeError` above was caused by a typo in
> ```python
> # Load from file
> with h5py.File(f, 'r') as r:
>     psi2 = hdf5_io.load_from_hdf5(r, psi)
> ```
which I correct as follows:
```python
# Load from file
with h5py.File(f, 'r') as r:
    psi2 = hdf5_io.load_from_hdf5(r)
```
where I removed the second argument `psi`, which should certainly not be passed to `path`.

**Comment by lukyluket** [comment]
Hallo there, I seem to have fallen again in this issue. 
I have some date I have written with h5py ver 2.1.0 and trying to read them with h5py 3.1.0 gave me the same error, 
I have downgraded to h5py 2.1.0 , I can read the file but I get errors when trying to write file to disk 
tenpy.tools.hdf5_io.Hdf5ExportError: Don't know how to save object of type <class 'numpy.dtype[float64]'>:
dtype('float64')

I am using 0.7.2, what should I do?
Cheers

**Comment by jhauschild** [comment]
Seems to be an issue with newer h5py versions. Let's discuss this in #124

**Comment by lukyluket** [comment]
Dear Johannes, I reinstalled on a new machine tenpy with the conda method,
and the bug appears again even though I have issued the update command
several time. Indeed the  hdf5_io.py file in tools does not contain the
modifications that fixes the bug-

Is there a way to automatically install the correct version from scratch or
do I have to install if from source?

Regards
Luca

**Comment by jhauschild** [comment]
Did you double check which tenpy version it installed? Are you sure you checked the right hdf5_io.py file?
The hdf5_io.py from version 0.8.4 distributed by conda is the same as the one from pip (by construction of the conda package), and it should have the fix...

**Comment by YuaZheH** [comment]
Dear Johannes, I seem to encounter the same bug in this issue,in which psi is a MPS instance

> ```python
> import tenpy
> import h5py
> from tenpy.networks.mps import MPS
> 
> with h5py.File('./data/example_1.h5', 'w') as f:
>     hdf5_saver = tenpy.tools.hdf5_io.Hdf5Saver(f)
>     subpath = "MPS_group/"
>     h5gr,subpath = hdf5_saver.create_group_for_obj(subpath,psi)
>     psi.save_hdf5(hdf5_saver, h5gr, subpath)
> 
> print(psi.bc)
> 
> hdf5_file_path = './data/example_1.h5'
> 
> 
> subpath = "MPS_group/"
> 
> with h5py.File(hdf5_file_path, 'r') as f:
>     hdf5_loader = tenpy.tools.hdf5_io.Hdf5Loader(f)
>     h5gr_1 = f[subpath]
>     mps = MPS.from_hdf5(hdf5_loader,h5gr_1, subpath)
>```
And get 
>ValueError: invalid boundary condition: "b'finite'"

I use conda to install all the packages, they are all latest versions.
